#!/usr/bin/env python3
"""refresh_teams — sync config/teams.json from Rocketlane Domain field.

Walks every active TEAM_MEMBER, reads the multi-value 'Domain' field from
their user record, and writes one cohort per domain. Multi-domain users
appear in each cohort they belong to. Also emits an `all-ps` superset
covering eDiscovery / Privacy / Post-Implementation / Forensics.

Run:
    python3 refresh_teams.py            # writes config/teams.json
    python3 refresh_teams.py --dry-run  # prints summary, no writes
    python3 refresh_teams.py --diff     # shows what would change

Domain → cohort key mapping is exact-match on the labels Rocketlane uses;
unknown domain values are flagged in the summary so we don't silently
drop users from cohorts when a label gets renamed.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import rocketlane_client as rl

REPO_ROOT = Path(__file__).resolve().parent
TEAMS_PATH = REPO_ROOT / "config" / "teams.json"

# Map: Rocketlane Domain label (exact) → cohort key in teams.json
DOMAIN_TO_COHORT = {
    "EDiscovery": "ediscovery",
    "Privacy": "privacy",
    "Post-Implementation": "post-impl",
    "Forensics": "forensics",
    "CSM / Non-PS": "csm",
    "Presales": "presales",
}

# Cohorts that compose the `all-ps` superset
ALL_PS_DOMAINS = {"EDiscovery", "Privacy", "Post-Implementation", "Forensics"}


def domains_for(user: dict) -> list[str]:
    """Return the list of Domain labels assigned to this user (multi-value)."""
    for f in user.get("fields") or []:
        if f.get("fieldLabel") == "Domain":
            label = f.get("fieldValueLabel") or ""
            # multi-value comes back as comma-joined, e.g. "EDiscovery,Privacy"
            return [d.strip() for d in label.split(",") if d.strip()]
    return []


def build_cohorts() -> tuple[dict[str, list[str]], dict]:
    """Return (cohorts, summary)."""
    pages = rl.fetch_users()
    all_users: list[dict] = []
    for p in pages:
        if isinstance(p, list):
            all_users.extend(p)

    cohorts: dict[str, set[str]] = defaultdict(set)
    unknown_labels: dict[str, int] = defaultdict(int)
    domain_counts: dict[str, int] = defaultdict(int)
    user_count = 0

    for u in all_users:
        if not isinstance(u, dict):
            continue
        if u.get("status") != "ACTIVE":
            continue
        if u.get("type") != "TEAM_MEMBER":
            continue
        email = (u.get("email") or "").lower()
        if not email or not email.endswith("@exterro.com"):
            continue
        user_count += 1
        domains = domains_for(u)
        if not domains:
            cohorts["_no-domain"].add(email)
            continue
        for dom in domains:
            domain_counts[dom] += 1
            key = DOMAIN_TO_COHORT.get(dom)
            if key is None:
                unknown_labels[dom] += 1
                continue
            cohorts[key].add(email)
            if dom in ALL_PS_DOMAINS:
                cohorts["all-ps"].add(email)

    # convert sets -> sorted lists
    final = {k: sorted(v) for k, v in cohorts.items()}
    summary = {
        "active_exterro_team_members": user_count,
        "domain_counts": dict(sorted(domain_counts.items(), key=lambda kv: -kv[1])),
        "unknown_labels": dict(unknown_labels),
        "cohort_sizes": {k: len(v) for k, v in sorted(final.items())},
    }
    return final, summary


def write_teams_file(cohorts: dict[str, list[str]]) -> None:
    existing: dict = {}
    if TEAMS_PATH.exists():
        try:
            existing = json.loads(TEAMS_PATH.read_text())
        except json.JSONDecodeError:
            existing = {}
    out = {
        "_comment": (
            "Group keyword -> list of member emails. Auto-generated by "
            "refresh_teams.py from Rocketlane Domain field. Edit "
            "DOMAIN_TO_COHORT in that script to add/rename keys."
        ),
    }
    # preserve any manual cohort that existed previously and isn't in our generated set
    for k, v in existing.items():
        if k.startswith("_"):
            continue
        if k not in cohorts and isinstance(v, list):
            out[k] = v  # keep manually curated cohorts as-is
    for k in sorted(cohorts.keys()):
        out[k] = cohorts[k]
    TEAMS_PATH.write_text(json.dumps(out, indent=2) + "\n")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--dry-run", action="store_true", help="Print summary, no writes")
    p.add_argument("--diff", action="store_true",
                   help="Show what would change vs current teams.json")
    args = p.parse_args(argv)

    if not rl.API_KEY:
        sys.stderr.write(
            "ERROR: ROCKETLANE_API_KEY not set. Expected in "
            f"{rl.SECRETS_FILE} or environment.\n"
        )
        return 5

    cohorts, summary = build_cohorts()

    print(f"Active Exterro team members scanned: {summary['active_exterro_team_members']}")
    print()
    print("Domain label counts (from Rocketlane):")
    for label, n in summary["domain_counts"].items():
        mapped = DOMAIN_TO_COHORT.get(label, "(unmapped)")
        print(f"  {label:30s} → {mapped:20s}  {n}")
    if summary["unknown_labels"]:
        print()
        print("WARN: Unknown Domain labels (not in DOMAIN_TO_COHORT):")
        for label, n in summary["unknown_labels"].items():
            print(f"  {label}: {n}")
    print()
    print("Resulting cohort sizes:")
    for k, n in summary["cohort_sizes"].items():
        print(f"  {k:14s} {n}")

    if args.diff and TEAMS_PATH.exists():
        try:
            current = json.loads(TEAMS_PATH.read_text())
        except json.JSONDecodeError:
            current = {}
        print()
        print("Diff vs current teams.json:")
        all_keys = set(current.keys()) | set(cohorts.keys())
        all_keys -= {k for k in all_keys if k.startswith("_")}
        for k in sorted(all_keys):
            old = set(current.get(k, []) or [])
            new = set(cohorts.get(k, []))
            added = sorted(new - old)
            removed = sorted(old - new)
            if not (added or removed):
                if k in cohorts:
                    print(f"  {k}: unchanged ({len(new)})")
                continue
            print(f"  {k}: {len(old)} → {len(new)}")
            for e in added:
                print(f"     + {e}")
            for e in removed:
                print(f"     - {e}")

    if args.dry_run:
        print()
        print("(dry-run — no file written)")
        return 0

    write_teams_file(cohorts)
    print()
    print(f"Wrote {TEAMS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
